name: flutter_fm
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.14.0 <3.0.0"

dependencies:
  auto_route: ^3.2.0
  components:
    path: packages/components
  connectivity_plus: ^2.1.0
  cores:
    path: packages/cores
  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  dio: ^4.0.4
  equatable: ^2.0.3
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.0
  flutter_localizations:
    sdk: flutter
  freezed_annotation: ^0.14.1
  get_it: ^7.2.0
  hive: ^2.0.5
  hive_flutter: ^1.1.0
  intl: ^0.17.0
  intl_generator: ^0.2.1
  orientation: ^1.3.0

dev_dependencies:
  auto_route_generator:
  build_runner:
  flutter_lints:
  flutter_test:
    sdk: flutter
  hive_generator: ^1.1.1
  json_serializable: ^6.1.3
  pedantic: ^1.11.1

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  generate: true
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/icons/

  fonts:
    - family: DMSans
      fonts:
        - asset: assets/fonts/DMSans/DMSans-Regular.ttf
          weight: 400
        - asset: assets/fonts/DMSans/DMSans-Medium.ttf
          weight: 500
        - asset: assets/fonts/DMSans/DMSans-Bold.ttf
          weight: 700