name: components
description: A new Flutter package project.
version: 0.0.1

environment:
  sdk: ">=2.15.1 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  badges: ^2.0.2
  cached_network_image: ^3.2.0
  flutter:
    sdk: flutter
  keyboard_actions: ^3.4.6
  rect_getter: ^1.1.0
  shimmer: ^2.0.0

dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter

flutter:
  generate: true
  uses-material-design: true

  assets:
    - ../../assets/images/
    - ../../assets/icons/

  fonts:
    - family: DMSans
      fonts:
        - asset: ../../assets/fonts/DMSans/DMSans-Regular.ttf
          weight: 400
        - asset: ../../assets/fonts/DMSans/DMSans-Medium.ttf
          weight: 500
        - asset: ../../assets/fonts/DMSans/DMSans-Bold.ttf
          weight: 700
